image: gitpod/workspace-full

github:
  # Prebuild the docker image for gitpod - https://www.gitpod.io/docs/46_prebuilds/
  prebuilds:
    # enable for the master/default branch
    master: true

tasks:
  - init: bundle install