language: ruby
rvm:
- 2.5
script:
- make -B _site
- if ! make test; then make test-warning; exit 16; fi
cache: bundler
notifications:
  slack:
    if: branch = master OR branch =~ ^.*slack.*$
    rooms:
      - secure: FN4trzyyUdtZ6DXj4G3A7YnhqkPyqi8jN9BIdA6S6D2eJEH1gPbZUfbqAW87LKckKZ9iYB5KDF5IuELhR3vv1DeHRqm3MKRU91JVBDT7EXbF86Z1J/JMJxNOcoWdCilcgpnm9NCkMAPFC9h6Y3txYhaLWLsnDaWlvehBsJg+Ql4=
    on_success: change
    on_failure: always
